name: 'MatterMost Weather Bot'
services:
  postgres:
    image: postgres:16-alpine
    container_name: mattermost-postgres
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
    volumes:
      - mattermost-postgres:/var/lib/postgresql/data
    networks:
      - mattermost-network

  mattermost:
    image: mattermost/mattermost-team-edition:latest
    container_name: mattermost-server
    depends_on:
      - postgres
    environment:
      # Database configuration
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:mmuser_password@postgres:5432/mattermost?sslmode=disable
      # Server settings
      - MM_SERVICESETTINGS_SITEURL=http://localhost:8065
      # SMTP settings (if needed)
      - MM_EMAILSETTINGS_ENABLESMTPAUTH=false
      - MM_EMAILSETTINGS_PUSHNOTIFICATIONCONTENTS=generic
      # File storage settings
      - MM_FILESETTINGS_DIRECTORY=/mattermost/data
      # Log settings
      - MM_LOGSETTINGS_ENABLEFILE=true
      - MM_LOGSETTINGS_FILENAME=/mattermost/logs/mattermost.log
    volumes:
      - mattermost-data:/mattermost/data
      - mattermost-logs:/mattermost/logs
      - mattermost-plugins:/mattermost/plugins
      - mattermost-client-plugins:/mattermost/client/plugins
      - mattermost-bleve-indexes:/mattermost/bleve-indexes
    ports:
      - "8065:8065"
    networks:
      - mattermost-network

volumes:
  mattermost-postgres:
  mattermost-data:
  mattermost-logs:
  mattermost-plugins:
  mattermost-client-plugins:
  mattermost-bleve-indexes:

networks:
  mattermost-network:
    driver: bridge
